### ISSUE TITLE
Android M like share dialog

### ISSUE THREAD

**Issue by tasomaniac** [ProxyApp/Proxy#18]
![image](https://cloud.githubusercontent.com/assets/763339/8003552/37331ac6-0b81-11e5-828d-fe6281137ea6.png)

When I was watching this on I/O keynote, Proxy app came to my mind. This is almost the same with the idea of Proxy. But it is not bad, because it will take >=1 year for this feature to be present on Android devices. 

So I am thinking the ways/hacks to implement this for older Android version. I think it is possible.

**Comment by vbucc** [comment]
I don't understand how this is applicable. Can you explain further?

**Comment by tasomaniac** [comment]
Are you asking how is this related to the idea of proxy? or are you asking how are we going to do this?

**Comment by vbucc** [comment]
How it's related to what Proxy is building now. I don't understand what the feature is.

**Comment by tasomaniac** [comment]
When you look at the screenshot you will see people with app preferences. If someone prefers Whatsapp it shares the content with that person using Whatsapp. Isn't proxy about social network preferences?

**Comment by vbucc** [comment]
I'd like to implement a feature for sharing a link to the proxy marketing website. I like the way that Android L does sharing, but I see how the ability to jump right to people with M is an improvement.

Want to help us add an "Invite Friends" button to our nav panel?
